export const FETCH_CARDS_BEGIN = 'FETCH_CARDS_BEGIN';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const UPDATE_SORT = 'UPDATE_SORT';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
